### ISSUE TITLE
切换章节提示 Loading 状态

### ISSUE THREAD

**Issue by martinx** [kanmaoxian/issues#1]
目前的现象：

如果服务器的章节内容返回慢的话，则会先停留在前一章节，然后一会突然切换到新的章节

重现步骤：

选择任意本书 -> 点击阅读 -> 点左下角 章节进行切换 （目前直接滑动章节是会显示 Loading 标志的）

期望的现象：

增加状态提示正在加载新章节

**Comment by serco-chen** [comment]
Fixed.
