### ISSUE TITLE
如果无章节，禁止阅读并给出提示

### ISSUE THREAD

**Issue by martinx** [kanmaoxian/issues#14]
重新步骤：

搜索 我的美女公寓 -> 点击 阅读

目前章节为空，所以无法阅读

>  http://120.26.42.29:1234/v1/books/34v9uz47syop6/chapters

期望解决：

一：服务端增加章节检查

目前图书信息中返回的最新章节不为空，但是章节目录为空。期望能检查，减少信息不对称的输出

二：客户端增加判断

如果章节加载为空，则给出提示，或者报错给服务器。人工可以检查，适当的手工更新。

**Comment by serco-chen** [comment]
Fixed.
