### ISSUE TITLE
注册登录

### ISSUE THREAD

**Issue by serco-chen** [kanmaoxian/issues#23]

**Comment by martinx** [comment]
API 已经更新了

~~https://yuesmart.github.io/mori-api-document/?ruby#part-6542d8cdced~~

**Comment by martinx** [comment]
更新文档只新的 repo和 org

https://kanmaoxian.github.io/api-doc/

**Comment by serco-chen** [comment]
@martinx 
注册的API为什么不直接把token返回呢？
不然注册成功就需要重新再请求下token了。

另外注册的时候为什么密码不是必须的？

**Comment by martinx** [comment]
@serco-chen 

已经修改注册 API，增加返回 token

```
{
  "data": {
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0OTIxNTkyNTcsInN1YiI6Mn0.3BdvRVgU_lystYTXDfFY30i46ou73ryO8PT_R4czZDI"
  },
  "meta": {
    "code": 10000,
    "message": "Success"
  }
}
```

另外也增加了密码校检

* 必需存在
* 长度至少6位

**Comment by serco-chen** [comment]
@martinx 登录有两个问题
1. 登录的时候没有验证密码，随便输就可以登录
2. 输入一个没有注册的手机号返回500

**Comment by martinx** [comment]
好的，我一会试试看

**Comment by serco-chen** [comment]
@martinx 登录时好像有问题，任意密码都能登录

**Comment by martinx** [comment]
没有哦，我登录不成功，发现 log 提示是 GET 请求的

```
GET "/v1/user_token?api_key=27bbb8c8-1993-49be-9baf-0f60e42b804c&app_version=1.0.0&platform=android"
```

应该是 POST 的，是我的版本问题吗？

**Comment by serco-chen** [comment]
到公司了看一下，我这边从一开始写的就是post

**Comment by martinx** [comment]
伤心，我的代码为了测试，直接如下写的

```
  def authenticate password
    #raise "账号或密码错误" unless self.valid_password? password
    true
  end
```

😢 

已经修复了
