### ISSUE TITLE
APP 统计及错误日志收集

### ISSUE THREAD

**Issue by martinx** [kanmaoxian/issues#27]
我们需要集成一个统计软件，主要想实现如下的目的：

## Version 1

* 客户统计
* 错误日志

## Version 2

* 用户习惯（如时长分析和使用习惯等）

---

**Comment by martinx** [comment]
增加字段 js_version

**Comment by serco-chen** [comment]
@martinx APK上传 504

**Comment by martinx** [comment]
js_version 已经增加

**Comment by martinx** [comment]
@serco-chen apk 已经改成异步上传了

**Comment by serco-chen** [comment]
报错时app已增加js_version信息
