### ISSUE TITLE
服务资源接口

### ISSUE THREAD

**Issue by martinx** [kanmaoxian/issues#30]
目前我们的接口请求是唯一的地址，如果此 IP 出现问题，或者我们迁移服务器，则需用户更新 APP。

考虑如下方案：

## 服务资源接口

独立一个域名接口，只提供可用服务地址资源（此接口不提供阅读本身的功能）

因为域名可配置成 round robin的模式，即支持多 IP，所以在此模式下，只要保证域名有效，就可以了。就算所有的 IP 都死了，最多24小时后也能刷新成新的 IP 地址。

Sample

```json
{
  "data": [
    "https://ip1:port",
    "https://ip2:port",
    "https://ip3:port"
  ],

  "meta": {
    "code": 10000,
    "message": "Success"
  }
}
```

**Comment by martinx** [comment]
@serco-chen 晓光，你觉得呢？

**Comment by martinx** [comment]
写了个静态 JSON 文件放在服务器上测试：

http://rs.yuesmart.com/index.json

**Comment by serco-chen** [comment]
我之前也考虑个这个问题，跟我想的差不多。但是客户端刷新这个服务器ip的这个接口该是什么频率比较好呢？

**Comment by martinx** [comment]
我的想法每次重新启动刷一次就好了，然后缓存在本地。你觉得呢？

**Comment by serco-chen** [comment]
@martin Apple 调整了审核规则，新上架的app走域名的请求必须是https

**Comment by martinx** [comment]
SSL 我已经配置好了，你试试看

https://api.maoxianapp.com/v1/books

明天我们讨论下这个问题。

**Comment by serco-chen** [comment]
证书是自签名的吗？直接访问就提示安全问题。

**Comment by martinx** [comment]
不是的，是用的那个免费的证书，不过我从他们的通知看到，Chrome
cont2016年将他们免费证书设为不可信的。看下这个能否通过，如果不能通过，我去购买个收费的证书。

https://www.startcomca.com/

我目前把附件中的证书安装到 key chain 中，显示是绿的:)

**Comment by serco-chen** [comment]
可以用let's encrypt, 域名现在是配在aliyun的服务器上吗？这个不需要备案吗？

**Comment by serco-chen** [comment]
@martinx 找到问题了。。原来是我很早之前修改的API请求方法里有个错误，chrome有这个api，模拟器没有。。。。

**Comment by martinx** [comment]
先在七牛上创建一个静态文件，手工维护，将 ip 地址放到上面

**Comment by martinx** [comment]
@serco-chen 我放了一个静态文件到七牛

https://o9j4saj3j.qnssl.com/kanmaoxian.json

你看下是否可以直接使用

**Comment by serco-chen** [comment]
Done.
