### ISSUE TITLE
无法显示正文

### ISSUE THREAD

**Issue by martinx** [kanmaoxian/issues#31]
服务器返回是正常的，但是在 APP 中一直提示加载中，不知道啥问题，先记录下。

http://120.26.42.29:1234/v1/books/2vpq7sd6v8b5z/chapters/kg4c?api_key=27bbb8c8-1993-49be-9baf-0f60e42b804c&app_version=1.0.0&platform=android

操作顺序：

> 检索《混沌剑神》 -> 点击阅读 -> 切换到章节 《第七百二十九章 无奈拜师》

如果新版没问题，直接关闭它:)

**Comment by serco-chen** [comment]
@martinx 我看一下，好像有一个issue你提错地方了，写到了qlear/issues里去了

**Comment by martinx** [comment]
额，好尴尬：）我去删除掉

**Comment by serco-chen** [comment]
@martinx 发布版本了，可以试一下这个问题还在吗
