### ISSUE TITLE
不请求服务器 

### ISSUE THREAD

**Issue by martinx** [kanmaoxian/issues#32]
很奇怪，操作过几次，然后无论操作什么按钮，服务器均无请求记录，APP 始终处于 loading 状态。

这两次有个共同特征就是 上次操作 loading 没结束/失败，返回再点其他资源。有可能请求是排他的，猜测:)

**Comment by serco-chen** [comment]
上传了个新版本，下载试试。还是老的[url](https://fir.im/kanmaoxian)

**Comment by serco-chen** [comment]
数据库换掉了，原来的本地数据会清空

**Comment by martinx** [comment]
好的，我试试看

**Comment by serco-chen** [comment]
由于代码在redux saga部分报错，block了后续 event handler的逻辑

1. 需要添加error handling 代码到saga部分
2. 将报错信息提交到服务器

@martinx 求一个自动报错api

**Comment by serco-chen** [comment]
关联 #36 先关闭这个。
