### ISSUE TITLE
点击章节出现内容加载的问题

### ISSUE THREAD

**Issue by martinx** [kanmaoxian/issues#33]
刚测试了新版，在测试点击章节查看的时候有如下的问题：

一：随机选择章节点击，会发现，内容不显示的几率很高（从日志上看服务器返回正常，截取 URL通过 web 访问也正常）

同 #31 ，这个问题之前提过，应该是一样的。

二：选择章节，有时候会发现当前显示的还是上一章的最后一页，如直接跳到90章节，发现显示的是89章的最后一页。这个不全部是，但是出现的几率也很高。

以上测试均以 《混沌剑神》测试的，选择章节随机选择的，有前几章，也有几百章，甚至上千章节的。

**Comment by serco-chen** [comment]
我测试新版也发现了一些问题，我去看下到底什么问题，快速翻页也会出现页面闪现后变白屏

**Comment by serco-chen** [comment]
二已经修复，一同 #31 ，这个issue先关闭了。问题一用 #31 来追踪。
