### ISSUE TITLE
上报 APP 异常信息

### ISSUE THREAD

**Issue by martinx** [kanmaoxian/issues#36]
> POST /v1/app_exceptions

我将异常信息稍微细化了下，这样便于后端统计

* app_verison App 的版本号，String
* platform 设备类型，iOS 或者 Android
* platform_version 设备版本号
* environment 设备其他环境信息，任意。 Text
* message 异常的摘要信息。Text
* backtrace 异常完整栈。Text
* request 用户当前所在的界面，任意自定义，便于定位问题。如 正在阅读界面，在首页等，任意字符。TEXT

**Comment by serco-chen** [comment]
@martinx 这个接口是已经做好了吗？

**Comment by serco-chen** [comment]
目前先把阅读界面的异步错误处理做了，其他部分先不做了。
