### ISSUE TITLE
资源重复请求

### ISSUE THREAD

**Issue by martinx** [kanmaoxian/issues#6]
目前现象：

看任意章节，点物理返回键退出 App，再次点击 App，自动显示上次阅读的界面，但是看到后台会再次重复其他资源，包括

* /v1/rankings
* /v1/rankings/{ranking_id}
* /v1/books/{book_id1}
* /v1/books/{book_id2}
* /v1/books/{book_id3}
* /v1/books/{book_id1}/recommended
* /v1/books/{book_id1}/chapters

这些内容应该是我刚刚点过，App 再次 Active 后，会再次全部加载一遍

**Comment by serco-chen** [comment]
Fixed.
